# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\asus\Documents\Alox\Computer Vision\Skripsi2\PyQT5\ui\AnalisisMenu.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1121, 790)
        Form.setMinimumSize(QtCore.QSize(690, 460))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        self.Background = QtWidgets.QWidget(Form)
        self.Background.setEnabled(True)
        self.Background.setGeometry(QtCore.QRect(0, 0, 1181, 821))
        self.Background.setStyleSheet("QWidget#Background{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(5, 0, 255, 0.8), stop:1 rgba(255, 255, 255, 255));\n"
" \n"
"}")
        self.Background.setObjectName("Background")
        self.frame = QtWidgets.QFrame(self.Background)
        self.frame.setGeometry(QtCore.QRect(170, 40, 871, 741))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.camera_view = QtWidgets.QGraphicsView(self.frame)
        self.camera_view.setGeometry(QtCore.QRect(10, 10, 851, 721))
        self.camera_view.setObjectName("camera_view")
        self.listWidget = QtWidgets.QListWidget(self.Background)
        self.listWidget.setGeometry(QtCore.QRect(10, 21, 141, 761))
        self.listWidget.setObjectName("listWidget")
        self.Refresh = QtWidgets.QPushButton(self.Background)
        self.Refresh.setGeometry(QtCore.QRect(40, 30, 75, 23))
        self.Refresh.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icons/arrow-circle-225.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Refresh.setIcon(icon)
        self.Refresh.setIconSize(QtCore.QSize(25, 25))
        self.Refresh.setFlat(True)
        self.Refresh.setObjectName("Refresh")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Background)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(1040, 30, 84, 741))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.otomatis = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.otomatis.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icons/clock.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.otomatis.setIcon(icon1)
        self.otomatis.setIconSize(QtCore.QSize(25, 25))
        self.otomatis.setFlat(True)
        self.otomatis.setObjectName("otomatis")
        self.verticalLayout.addWidget(self.otomatis)
        self.Open_cam = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Open_cam.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../icons/unlocked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Open_cam.setIcon(icon2)
        self.Open_cam.setIconSize(QtCore.QSize(25, 25))
        self.Open_cam.setFlat(True)
        self.Open_cam.setObjectName("Open_cam")
        self.verticalLayout.addWidget(self.Open_cam)
        self.Click_photo = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Click_photo.setAutoFillBackground(False)
        self.Click_photo.setStyleSheet("")
        self.Click_photo.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../icons/camera.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Click_photo.setIcon(icon3)
        self.Click_photo.setIconSize(QtCore.QSize(30, 30))
        self.Click_photo.setAutoDefault(False)
        self.Click_photo.setDefault(False)
        self.Click_photo.setFlat(True)
        self.Click_photo.setObjectName("Click_photo")
        self.verticalLayout.addWidget(self.Click_photo)
        self.Open_folder = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Open_folder.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../icons/folder.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Open_folder.setIcon(icon4)
        self.Open_folder.setIconSize(QtCore.QSize(25, 25))
        self.Open_folder.setAutoDefault(False)
        self.Open_folder.setDefault(False)
        self.Open_folder.setFlat(True)
        self.Open_folder.setObjectName("Open_folder")
        self.verticalLayout.addWidget(self.Open_folder)
        self.Setting_cam = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Setting_cam.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../icons/gear.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Setting_cam.setIcon(icon5)
        self.Setting_cam.setIconSize(QtCore.QSize(25, 25))
        self.Setting_cam.setFlat(True)
        self.Setting_cam.setObjectName("Setting_cam")
        self.verticalLayout.addWidget(self.Setting_cam)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Refresh.setShortcut(_translate("Form", "R"))
        self.otomatis.setToolTip(_translate("Form", "Open Cam"))
        self.Open_cam.setToolTip(_translate("Form", "Open Cam"))
        self.Click_photo.setToolTip(_translate("Form", "Photo"))
        self.Open_folder.setToolTip(_translate("Form", "Open Folder"))
        self.Setting_cam.setToolTip(_translate("Form", "Setting Camera"))

